/* The following code was generated by JFlex 1.4.3 on 12/19/13 6:44 PM */

package com.github.mensajeria.compiler.servidor;

import com.github.mensajeria.compiler.Err;
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import java.lang.StringBuilder;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/19/13 6:44 PM from the specification file
 * <tt>./src/servidor/scanner.jflex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\4\1\3\1\1\2\0\1\2\16\4\4\0\1\3\1\0\1\46"+
    "\1\27\1\5\1\25\2\0\1\30\1\32\3\0\1\0\2\0\12\4"+
    "\1\0\1\45\1\0\1\44\1\0\1\26\1\0\1\37\2\5\1\41"+
    "\11\5\1\40\1\35\2\5\1\36\10\5\4\0\1\5\1\0\1\12"+
    "\1\15\1\16\1\34\1\11\1\5\1\31\1\5\1\20\1\24\1\5"+
    "\1\13\1\17\1\21\1\23\1\22\1\5\1\7\1\14\1\6\1\10"+
    "\1\5\1\33\3\5\1\42\1\0\1\43\1\0\41\4\2\0\4\5"+
    "\4\0\1\5\2\0\1\4\7\0\1\5\4\0\1\5\5\0\27\5"+
    "\1\0\37\5\1\0\u01ca\5\4\0\14\5\16\0\5\5\7\0\1\5"+
    "\1\0\1\5\21\0\160\4\5\5\1\0\2\5\2\0\4\5\10\0"+
    "\1\5\1\0\3\5\1\0\1\5\1\0\24\5\1\0\123\5\1\0"+
    "\213\5\1\0\5\4\2\0\236\5\11\0\46\5\2\0\1\5\7\0"+
    "\47\5\11\0\55\4\1\0\1\4\1\0\2\4\1\0\2\4\1\0"+
    "\1\4\10\0\33\5\5\0\3\5\15\0\4\4\7\0\1\5\4\0"+
    "\13\4\5\0\53\5\37\4\4\0\2\5\1\4\143\5\1\0\1\5"+
    "\10\4\1\0\6\4\2\5\2\4\1\0\4\4\2\5\12\4\3\5"+
    "\2\0\1\5\17\0\1\4\1\5\1\4\36\5\33\4\2\0\131\5"+
    "\13\4\1\5\16\0\12\4\41\5\11\4\2\5\4\0\1\5\5\0"+
    "\26\5\4\4\1\5\11\4\1\5\3\4\1\5\5\4\22\0\31\5"+
    "\3\4\244\0\4\4\66\5\3\4\1\5\22\4\1\5\7\4\12\5"+
    "\2\4\2\0\12\4\1\0\7\5\1\0\7\5\1\0\3\4\1\0"+
    "\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\1\5\3\0"+
    "\4\5\2\0\1\4\1\5\7\4\2\0\2\4\2\0\3\4\1\5"+
    "\10\0\1\4\4\0\2\5\1\0\3\5\2\4\2\0\12\4\4\5"+
    "\7\0\1\5\5\0\3\4\1\0\6\5\4\0\2\5\2\0\26\5"+
    "\1\0\7\5\1\0\2\5\1\0\2\5\1\0\2\5\2\0\1\4"+
    "\1\0\5\4\4\0\2\4\2\0\3\4\3\0\1\4\7\0\4\5"+
    "\1\0\1\5\7\0\14\4\3\5\1\4\13\0\3\4\1\0\11\5"+
    "\1\0\3\5\1\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5"+
    "\2\0\1\4\1\5\10\4\1\0\3\4\1\0\3\4\2\0\1\5"+
    "\17\0\2\5\2\4\2\0\12\4\1\0\1\5\17\0\3\4\1\0"+
    "\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0"+
    "\5\5\2\0\1\4\1\5\7\4\2\0\2\4\2\0\3\4\10\0"+
    "\2\4\4\0\2\5\1\0\3\5\2\4\2\0\12\4\1\0\1\5"+
    "\20\0\1\4\1\5\1\0\6\5\3\0\3\5\1\0\4\5\3\0"+
    "\2\5\1\0\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0"+
    "\14\5\4\0\5\4\3\0\3\4\1\0\4\4\2\0\1\5\6\0"+
    "\1\4\16\0\12\4\11\0\1\5\7\0\3\4\1\0\10\5\1\0"+
    "\3\5\1\0\27\5\1\0\12\5\1\0\5\5\3\0\1\5\7\4"+
    "\1\0\3\4\1\0\4\4\7\0\2\4\1\0\2\5\6\0\2\5"+
    "\2\4\2\0\12\4\22\0\2\4\1\0\10\5\1\0\3\5\1\0"+
    "\27\5\1\0\12\5\1\0\5\5\2\0\1\4\1\5\7\4\1\0"+
    "\3\4\1\0\4\4\7\0\2\4\7\0\1\5\1\0\2\5\2\4"+
    "\2\0\12\4\1\0\2\5\17\0\2\4\1\0\10\5\1\0\3\5"+
    "\1\0\51\5\2\0\1\5\7\4\1\0\3\4\1\0\4\4\1\5"+
    "\10\0\1\4\10\0\2\5\2\4\2\0\12\4\12\0\6\5\2\0"+
    "\2\4\1\0\22\5\3\0\30\5\1\0\11\5\1\0\1\5\2\0"+
    "\7\5\3\0\1\4\4\0\6\4\1\0\1\4\1\0\10\4\22\0"+
    "\2\4\15\0\60\5\1\4\2\5\7\4\4\0\10\5\10\4\1\0"+
    "\12\4\47\0\2\5\1\0\1\5\2\0\2\5\1\0\1\5\2\0"+
    "\1\5\6\0\4\5\1\0\7\5\1\0\3\5\1\0\1\5\1\0"+
    "\1\5\2\0\2\5\1\0\4\5\1\4\2\5\6\4\1\0\2\4"+
    "\1\5\2\0\5\5\1\0\1\5\1\0\6\4\2\0\12\4\2\0"+
    "\2\5\42\0\1\5\27\0\2\4\6\0\12\4\13\0\1\4\1\0"+
    "\1\4\1\0\1\4\4\0\2\4\10\5\1\0\44\5\4\0\24\4"+
    "\1\0\2\4\5\5\13\4\1\0\44\4\11\0\1\4\71\0\53\5"+
    "\24\4\1\5\12\4\6\0\6\5\4\4\4\5\3\4\1\5\3\4"+
    "\2\5\7\4\3\5\4\4\15\5\14\4\1\5\17\4\2\0\46\5"+
    "\12\0\53\5\1\0\1\5\3\0\u0149\5\1\0\4\5\2\0\7\5"+
    "\1\0\1\5\1\0\4\5\2\0\51\5\1\0\4\5\2\0\41\5"+
    "\1\0\4\5\2\0\7\5\1\0\1\5\1\0\4\5\2\0\17\5"+
    "\1\0\71\5\1\0\4\5\2\0\103\5\2\0\3\4\40\0\20\5"+
    "\20\0\125\5\14\0\u026c\5\2\0\21\5\1\0\32\5\5\0\113\5"+
    "\3\0\3\5\17\0\15\5\1\0\4\5\3\4\13\0\22\5\3\4"+
    "\13\0\22\5\2\4\14\0\15\5\1\0\3\5\1\0\2\4\14\0"+
    "\64\5\40\4\3\0\1\5\3\0\2\5\1\4\2\0\12\4\41\0"+
    "\3\4\2\0\12\4\6\0\130\5\10\0\51\5\1\4\1\5\5\0"+
    "\106\5\12\0\35\5\3\0\14\4\4\0\14\4\12\0\12\4\36\5"+
    "\2\0\5\5\13\0\54\5\4\0\21\4\7\5\2\4\6\0\12\4"+
    "\46\0\27\5\5\4\4\0\65\5\12\4\1\0\35\4\2\0\13\4"+
    "\6\0\12\4\15\0\1\5\130\0\5\4\57\5\21\4\7\5\4\0"+
    "\12\4\21\0\11\4\14\0\3\4\36\5\12\4\3\0\2\5\12\4"+
    "\6\0\46\5\16\4\14\0\44\5\24\4\10\0\12\4\3\0\3\5"+
    "\12\4\44\5\122\0\3\4\1\0\25\4\4\5\1\4\4\5\1\4"+
    "\15\0\300\5\47\4\25\0\4\4\u0116\5\2\0\6\5\2\0\46\5"+
    "\2\0\6\5\2\0\10\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\37\5\2\0\65\5\1\0\7\5\1\0\1\5\3\0\3\5"+
    "\1\0\7\5\3\0\4\5\2\0\6\5\4\0\15\5\5\0\3\5"+
    "\1\0\7\5\16\0\5\4\32\0\5\4\20\0\2\5\23\0\1\5"+
    "\13\0\5\4\5\0\6\4\1\0\1\5\15\0\1\5\20\0\15\5"+
    "\3\0\32\5\26\0\15\4\4\0\1\4\3\0\14\4\21\0\1\5"+
    "\4\0\1\5\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5"+
    "\5\0\5\5\4\0\1\5\21\0\51\5\u0a77\0\57\5\1\0\57\5"+
    "\1\0\205\5\6\0\4\5\3\4\16\0\46\5\12\0\66\5\11\0"+
    "\1\5\17\0\1\4\27\5\11\0\7\5\1\0\7\5\1\0\7\5"+
    "\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5"+
    "\1\0\40\4\57\0\1\5\u01d5\0\3\5\31\0\11\5\6\4\1\0"+
    "\5\5\2\0\5\5\4\0\126\5\2\0\2\4\2\0\3\5\1\0"+
    "\132\5\1\0\4\5\5\0\51\5\3\0\136\5\21\0\33\5\65\0"+
    "\20\5\u0200\0\u19b6\5\112\0\u51cc\5\64\0\u048d\5\103\0\56\5\2\0"+
    "\u010d\5\3\0\20\5\12\4\2\5\24\0\57\5\1\4\14\0\2\4"+
    "\1\0\31\5\10\0\120\5\2\4\45\0\11\5\2\0\147\5\2\0"+
    "\4\5\1\0\2\5\16\0\12\5\120\0\10\5\1\4\3\5\1\4"+
    "\4\5\1\4\27\5\5\4\20\0\1\5\7\0\64\5\14\0\2\4"+
    "\62\5\21\4\13\0\12\4\6\0\22\4\6\5\3\0\1\5\4\0"+
    "\12\4\34\5\10\4\2\0\27\5\15\4\14\0\35\5\3\0\4\4"+
    "\57\5\16\4\16\0\1\5\12\4\46\0\51\5\16\4\11\0\3\5"+
    "\1\4\10\5\2\4\2\0\12\4\6\0\27\5\3\0\1\5\1\4"+
    "\4\0\60\5\1\4\1\5\3\4\2\5\2\4\5\5\2\4\1\5"+
    "\1\4\1\5\30\0\3\5\43\0\6\5\2\0\6\5\2\0\6\5"+
    "\11\0\7\5\1\0\7\5\221\0\43\5\10\4\1\0\2\4\2\0"+
    "\12\4\6\0\u2ba4\5\14\0\27\5\4\0\61\5\u2104\0\u012e\5\2\0"+
    "\76\5\2\0\152\5\46\0\7\5\14\0\5\5\5\0\1\5\1\4"+
    "\12\5\1\0\15\5\1\0\5\5\1\0\1\5\1\0\2\5\1\0"+
    "\2\5\1\0\154\5\41\0\u016b\5\22\0\100\5\2\0\66\5\50\0"+
    "\15\5\3\0\20\4\20\0\7\4\14\0\2\5\30\0\3\5\31\0"+
    "\1\5\6\0\5\5\1\0\207\5\2\0\1\4\4\0\1\5\13\0"+
    "\12\4\7\0\32\5\4\0\1\5\1\0\32\5\13\0\131\5\3\0"+
    "\6\5\2\0\6\5\2\0\6\5\2\0\3\5\3\0\2\5\3\0"+
    "\2\5\22\0\3\4\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\5\3\1\4\1\5\1\6\1\1"+
    "\2\3\1\7\1\10\1\11\1\12\1\13\4\3\4\0"+
    "\1\14\6\3\4\0\1\15\5\3\4\0\5\3\4\0"+
    "\2\3\1\16\2\3\4\0\3\3\1\17\1\0\1\20"+
    "\2\0\1\21\1\3\1\22\1\0\1\23\1\0\1\24"+
    "\1\25\1\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\116\0\165\0\234\0\303\0\352"+
    "\0\u0111\0\u0138\0\116\0\116\0\116\0\u015f\0\u0186\0\u01ad"+
    "\0\116\0\116\0\116\0\116\0\116\0\u01d4\0\u01fb\0\u0222"+
    "\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\234\0\u030c\0\u0333"+
    "\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b"+
    "\0\234\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c"+
    "\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666\0\u068d\0\u06b4"+
    "\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\234\0\u079e\0\u07c5"+
    "\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6\0\234"+
    "\0\u08fd\0\116\0\u0924\0\u094b\0\234\0\u0972\0\234\0\u0999"+
    "\0\116\0\u09c0\0\234\0\116\0\u09e7\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\4\1\3\2\6\1\7\5\6"+
    "\1\10\1\11\1\12\5\6\1\13\1\14\1\15\1\16"+
    "\1\6\1\3\2\6\1\17\1\6\1\20\2\6\1\21"+
    "\1\22\1\23\1\24\1\25\47\3\50\0\1\4\51\0"+
    "\21\6\4\0\1\6\1\0\7\6\11\0\5\6\1\26"+
    "\13\6\4\0\1\6\1\0\7\6\11\0\4\6\1\27"+
    "\14\6\4\0\1\6\1\0\7\6\11\0\17\6\1\30"+
    "\1\6\4\0\1\6\1\0\7\6\11\0\5\6\1\31"+
    "\13\6\4\0\1\6\1\0\7\6\15\0\1\32\2\0"+
    "\1\33\2\0\1\34\3\0\1\35\30\0\21\6\4\0"+
    "\1\6\1\0\3\6\1\36\3\6\11\0\21\6\4\0"+
    "\1\6\1\0\5\6\1\37\1\6\11\0\12\6\1\40"+
    "\1\41\5\6\4\0\1\6\1\0\7\6\11\0\10\6"+
    "\1\42\10\6\4\0\1\6\1\0\7\6\11\0\15\6"+
    "\1\43\3\6\4\0\1\6\1\0\7\6\11\0\15\6"+
    "\1\44\3\6\4\0\1\6\1\0\7\6\21\0\1\45"+
    "\55\0\1\46\33\0\1\47\50\0\1\50\40\0\21\6"+
    "\4\0\1\6\1\0\6\6\1\51\11\0\5\6\1\52"+
    "\13\6\4\0\1\6\1\0\7\6\11\0\14\6\1\53"+
    "\4\6\4\0\1\6\1\0\7\6\11\0\12\6\1\54"+
    "\6\6\4\0\1\6\1\0\7\6\11\0\2\6\1\55"+
    "\16\6\4\0\1\6\1\0\7\6\11\0\10\6\1\56"+
    "\10\6\4\0\1\6\1\0\7\6\15\0\1\57\67\0"+
    "\1\60\26\0\1\61\51\0\1\62\36\0\16\6\1\63"+
    "\2\6\4\0\1\6\1\0\7\6\11\0\2\6\1\64"+
    "\16\6\4\0\1\6\1\0\7\6\11\0\6\6\1\65"+
    "\12\6\4\0\1\6\1\0\7\6\11\0\14\6\1\66"+
    "\4\6\4\0\1\6\1\0\7\6\11\0\6\6\1\67"+
    "\12\6\4\0\1\6\1\0\7\6\17\0\1\70\54\0"+
    "\1\71\47\0\1\72\41\0\1\73\36\0\2\6\1\74"+
    "\16\6\4\0\1\6\1\0\7\6\11\0\5\6\1\75"+
    "\13\6\4\0\1\6\1\0\7\6\11\0\3\6\1\76"+
    "\15\6\4\0\1\6\1\0\7\6\11\0\5\6\1\77"+
    "\13\6\4\0\1\6\1\0\7\6\11\0\20\6\1\100"+
    "\4\0\1\6\1\0\7\6\14\0\1\101\60\0\1\102"+
    "\33\0\1\103\73\0\1\104\17\0\17\6\1\105\1\6"+
    "\4\0\1\6\1\0\7\6\11\0\15\6\1\106\3\6"+
    "\4\0\1\6\1\0\7\6\11\0\15\6\1\107\3\6"+
    "\4\0\1\6\1\0\7\6\11\0\5\6\1\110\13\6"+
    "\4\0\1\6\1\0\7\6\25\0\1\111\60\0\1\112"+
    "\26\0\1\113\57\0\1\114\27\0\3\6\1\115\15\6"+
    "\4\0\1\6\1\0\7\6\11\0\2\6\1\116\16\6"+
    "\4\0\1\6\1\0\7\6\11\0\5\6\1\117\13\6"+
    "\4\0\1\6\1\0\7\6\30\0\1\120\55\0\1\121"+
    "\23\0\1\122\43\0\5\6\1\123\13\6\4\0\1\6"+
    "\1\0\7\6\37\0\1\124\50\0\1\125\44\0\1\126"+
    "\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2574];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\6\1\3\11\3\1\5\11\4\1\4\0"+
    "\7\1\4\0\6\1\4\0\5\1\4\0\5\1\4\0"+
    "\4\1\1\0\1\11\2\0\3\1\1\0\1\11\1\0"+
    "\1\1\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /** Errores **/
    public LinkedList<Err> errores=new LinkedList<>();
    private void error(String message) {
            
        Symbol sym=new Symbol(Sym.error, yyline, yycolumn, yytext());
        Err e=new Err(message,sym,Err.TIPO.LEXICO);
        errores.add(e);
    }
    /** String **/
    StringBuilder string=new StringBuilder();

    /** Symbol **/
    
    private Symbol symbol(int type) {
            return new Symbol(type, yyline, yycolumn,yytext());
    }
    private Symbol symbol(int type, Object value) {
            return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2208) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { return symbol(Sym.EQUAL);
          }
        case 23: break;
        case 19: 
          { return symbol(Sym.ST_CUENTA);
          }
        case 24: break;
        case 6: 
          { return symbol(Sym.NUMERAL);
          }
        case 25: break;
        case 7: 
          { return symbol(Sym.LL1);
          }
        case 26: break;
        case 13: 
          { return symbol(Sym.AND);
          }
        case 27: break;
        case 16: 
          { return symbol(Sym.ST_LOGIN);
          }
        case 28: break;
        case 15: 
          { return symbol(Sym.MENSAJE);
          }
        case 29: break;
        case 17: 
          { return symbol(Sym.RECEPTOR);
          }
        case 30: break;
        case 3: 
          { return symbol(Sym.ID);
          }
        case 31: break;
        case 14: 
          { return symbol(Sym.BUSCAR);
          }
        case 32: break;
        case 11: 
          { return symbol(Sym.QUOTE);
          }
        case 33: break;
        case 18: 
          { return symbol(Sym.CONTIENE);
          }
        case 34: break;
        case 10: 
          { return symbol(Sym.PCOMA);
          }
        case 35: break;
        case 21: 
          { return symbol(Sym.ST_USUARIO);
          }
        case 36: break;
        case 22: 
          { return symbol(Sym.ST_PASSWORD);
          }
        case 37: break;
        case 8: 
          { return symbol(Sym.LL2);
          }
        case 38: break;
        case 20: 
          { return symbol(Sym.REMITENTE);
          }
        case 39: break;
        case 4: 
          { return symbol(Sym.PERCENT);
          }
        case 40: break;
        case 1: 
          { error("Illegal character.");
          }
        case 41: break;
        case 5: 
          { return symbol(Sym.CLOSEQ);
          }
        case 42: break;
        case 2: 
          { 
          }
        case 43: break;
        case 12: 
          { return symbol(Sym.OR);
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(Sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
