
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 19 18:42:45 CST 2013
//----------------------------------------------------

package com.github.mensajeria.compiler.servidor;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int AND = 9;
  public static final int PERCENT = 19;
  public static final int OR = 10;
  public static final int EQUAL = 11;
  public static final int LP = 2;
  public static final int RP = 3;
  public static final int ST_LOGIN = 22;
  public static final int ST_RECEPTOR = 26;
  public static final int ST_PASSWORD = 25;
  public static final int ID = 4;
  public static final int ST_EMISOR = 27;
  public static final int QUOTE = 17;
  public static final int ST_USUARIO = 24;
  public static final int EOF = 0;
  public static final int REMITENTE = 13;
  public static final int FECHA = 12;
  public static final int RECEPTOR = 14;
  public static final int BUSCAR = 7;
  public static final int error = 1;
  public static final int CONTIENE = 16;
  public static final int ST_MENSAJE = 23;
  public static final int ST_CUENTA = 21;
  public static final int LL2 = 6;
  public static final int LL1 = 5;
  public static final int PCOMA = 8;
  public static final int CLOSEQ = 20;
  public static final int NUMERAL = 18;
  public static final int MENSAJE = 15;
}

