
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 19 17:15:26 CST 2013
//----------------------------------------------------

package com.github.mensajeria.compiler.servidor;

/** CUP generated class containing symbol constants. */
public class Sym_file {
  /* terminals */
  public static final int INT = 16;
  public static final int EQUAL = 7;
  public static final int LP = 2;
  public static final int RP = 3;
  public static final int CONTACTO = 19;
  public static final int EMISOR = 10;
  public static final int ID = 4;
  public static final int FECHA_HORA = 22;
  public static final int CONTACTOS = 21;
  public static final int EOF = 0;
  public static final int ANY = 8;
  public static final int CUENTA = 5;
  public static final int FECHA = 14;
  public static final int RECEPTOR = 12;
  public static final int PASSWORD = 13;
  public static final int NERROR = 20;
  public static final int error = 1;
  public static final int USUARIO = 6;
  public static final int DIAGONAL = 17;
  public static final int DPUNTO = 18;
  public static final int CONTENIDO = 15;
  public static final int PCOMA = 9;
  public static final int MENSAJE = 11;
}

